### ISSUE TITLE
Simple file converted (via archetype and Why3) to Coq giving error

### ISSUE THREAD

**Issue by Coda-Coda** [completium/vscode-archetype#8]
Hi,

After compiling the file below and trying to prove `test'VC` in why3 using Coq. The generated Coq file fails on:

```
(* Why3 assumption *)
Definition arstring := BuiltIn.string.
```
Giving the error
```
The reference BuiltIn.string
was not found in the current
environment.
```

Any pointers would be appreciated. I realise this might be a Why3-specific issue but thought I'd ask here as it might be a problem common to other (more complex) archetype generated why3/Coq files.

File:
```
archetype trivial_test

entry exec () {
  effect {
    ()
  }
}

function test(x : int) : bool {
  specification {
    postcondition testSpec {
      result = true <-> x < 10
    }
  }
  
  effect {
   if x < 10 then (
      return true
    ) else (
      return false
    )
  } 
}
```

**Comment by rognierbenoit** [comment]
Hi Coda,

you need to install the opam package `why3-coq`
```opam install why3-coq```

it should be the 1.3.1 version of  it.

**Comment by Coda-Coda** [comment]
Hi,

I do have `why3-coq` 1.3.1 installed. I have it installed not directly from opam due the [this issue](https://lists.gforge.inria.fr/pipermail/why3-club/2020-September/002247.html).

```
% opam install why3-coq

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><>  🐫 
[why3-coq.1.3.1] no changes from git+file:///Users/.../Why3WithBugfix/why3#bugfix/v1.3

[NOTE] Package why3-coq is already installed (current version is 1.3.1).
```

**Comment by Coda-Coda** [comment]
Hmm, I tried reinstalling why3 and why3-coq a few different ways but now I get the following error.

```
% why3 ide trivial_test.mlw
Fatal error while loading driver file 'coq': File "", line 1, characters 0-0:
                                             anomaly: Sys_error("Is a directory")
```

**Comment by Coda-Coda** [comment]
@rognierbenoit could you please confirm for me whether the fact that
```
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require int.Int.
```
all are processed fine by Coq shows that why3-coq is working or not?

I'm just struggling to get
```
Definition arstring := BuiltIn.string.
```
and
```
Axiom from_int_spec :
  forall (i:Numbers.BinNums.Z), ((from_int1 i) = (from_int i)).
```
and so on to be processed successfully by Coq.

Thanks for the help.

**Comment by Coda-Coda** [comment]
Hi @rognierbenoit,

Both https://gitlab.inria.fr/why3/why3/-/blob/master/examples/tests-provers/coq.why and https://gitlab.inria.fr/why3/why3/-/blob/master/examples/tests-provers/coq-interval.why compile OK via my Why3 setup with Coq which makes me think why3-coq is working.

Do you think it might be some other issue?

**Comment by Dr-McFish** [comment]
I Have the same problem here

**Comment by rognierbenoit** [comment]
Hi @Dr-McFish, archetype does not provide why3 generation anymore. If your issue is about the why3 bridge to coq, you should ask via the [why3 club mailing list](https://groupes.renater.fr/sympa/subscribe/why3-club?previous_action=info).
